// Generated by Selenium IDE
const { Builder, By, Key, until } = require("selenium-webdriver");
const assert = require("assert");

describe("searchTest", function () {
  this.timeout(30000);
  let driver;
  let vars;
  beforeEach(async function () {
    driver = await new Builder().forBrowser("chrome").build();
    vars = {};
  });
  afterEach(async function () {
    await driver.quit();
  });
  it("searchTest", async function () {
    await driver.get("https://qualitydemy.com/");
    await driver.manage().window().setRect({ width: 1440, height: 875 });
    await driver.findElement(By.name("query")).click();
    await driver.findElement(By.name("query")).sendKeys("react");
    await driver.findElement(By.name("query")).sendKeys(Key.ENTER);
    await driver.findElement(By.linkText("React and Typescript")).click();
    await driver.findElement(By.css(".course-header-wrap > .title")).click();
    await driver.wait(
      until.elementIsVisible(
        await driver.findElement(By.css(".course-header-wrap > .title"))
      ),
      4000
    );
    assert(
      (await driver
        .findElement(By.css(".course-header-wrap > .title"))
        .getText()) == "React and Typescript"
    );
  });
});
